### ISSUE TITLE
大约加载到第九页时数组越界异常

### ISSUE THREAD

**Issue by imcloud** [taxeric/PokeCompose#1]
```java
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.lanier.foxcomposepractice.ui.theme.screen.PokemonInfoScreenKt.ShowInfo(PokemonInfoScreen.kt:156)
        at com.lanier.foxcomposepractice.ui.theme.screen.PokemonInfoScreenKt.LoadFinish-Bx497Mc(PokemonInfoScreen.kt:132)
        at com.lanier.foxcomposepractice.ui.theme.screen.PokemonInfoScreenKt.MainInfo(PokemonInfoScreen.kt:85)
        at com.lanier.foxcomposepractice.ui.theme.screen.PokemonInfoScreenKt$MainInfo$5.invoke(Unknown Source:10)
        at com.lanier.foxcomposepractice.ui.theme.screen.PokemonInfoScreenKt$MainInfo$5.invoke(Unknown Source:10)
```

**Comment by taxeric** [comment]
您好，我将在晚上看一下

**Comment by taxeric** [comment]
您好，感谢您的issue，已更新
